version: '3'


services:

  gateway:
    container_name: gateway
    build:
      context: .
      dockerfile: ./apps/gateway/Dockerfile
#    command:
#      - npm run db:migrate
#      - npm run start:dev gateway
    env_file:
      - ./apps/gateway/.env
    depends_on:
      - meetup-db
      - auth-db
      - auth
      - meetup
      - rabbitmq
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000

  auth:
    container_name: auth
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
#    command:
#      - npm run start:dev auth
    env_file:
      - ./apps/auth/.env
    depends_on:
      - auth-db
      - rabbitmq
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  meetup:
    container_name: meetup
    build:
      context: .
      dockerfile: ./apps/meetup/Dockerfile
#    command:
#      - npm run start:dev meetup
    env_file:
      - ./apps/meetup/.env
    depends_on:
      - meetup-db
      - auth-db
      - rabbitmq
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  meetup-db:
    container_name: meetup-db
    image: postgres:latest
    restart: always
    env_file:
      - ./apps/meetup/.env
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - meetup-db-data:/var/lib/postgresql/data
    ports:
      - 5433:5433
    networks:
      - mynetwork

  auth-db:
    container_name: auth-db
    image: postgres:latest
    restart: always
    env_file:
      - ./apps/auth/.env
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - auth-db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - mynetwork

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - mynetwork

volumes:
  meetup-db-data:
  auth-db-data:

networks:
  mynetwork:
    driver: bridge